### ISSUE TITLE
Example usage

### ISSUE THREAD

**Issue by berkantay** [ami-a/TrackEverything#1]
hello @ami-a have you got any tracking example code. Because I have my detection model and I can extract the bounding box of the object that I want to detect. I just want to pass the bounding box to the CSRT or MOSSE tracker. How can I do this?

**Comment by ami-a** [comment]
I provide a few links for examples in the Readme.md file, in those examples, I use independent models and add tracking (specifically in those I use CSRT tracker(the default I've set) but you can use many more). You only need to provide your detection model and specify a function that interpolates your model's output to the same output format of the default variable detection_proccessing in the DetectionVars, then you provide to the Detector Class your DetectionVars.
